spring.application.name=backend

# MariaDB
spring.datasource.url=jdbc:mariadb://${DB_HOST:172.30.48.22}:${DB_PORT:3306}/${DB_NAME:dangwalk}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
spring.datasource.username=${DB_USERNAME:dw1}
spring.datasource.password=${DB_PASSWORD:1234}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
