spring.application.name=backend

# MariaDB 연결 설정 (환경변수 사용)
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&connectTimeout=60000&socketTimeout=60000
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# HikariCP
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.validation-timeout=10000
spring.datasource.hikari.maximum-pool-size=10

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# 반려견 동반 장소 공공데이터 OpenAPI (JSON)
app.place.api-url=https://api.odcloud.kr/api/15111389/v1/uddi:41944402-8249-4e45-9e9d-a52d0a7db1cc
app.place.service-key=${PUBLIC_DATA_SERVICE_KEY}
app.place.per-page=1000

# 카카오 키
kakao.rest-api-key=${KAKAO_REST_API_KEY}

# 카카오 지오코딩 호출량 설정
app.geocode.batch-size=10
app.geocode.sleep-ms=500
